language: node_js
node_js:
- 8
addons:
  chrome: beta
  apt:
    packages:
    - bc
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq $JQ_BINARY && chmod +x ~/bin/jq
- "./manage ci"
env:
  global:
  - JQ_BINARY="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
  - PATH="/usr/bin:$PATH"
  - secure: dPjo4DDXiObuijWlnEM85t8IAIxGVeQ6JS7YTQGMjfvR5B/c0aIUUt3XVbF6yINUOyXSy4vTcm11MdMlLRG2JG0hm9d3oLyfha/R9y1zihKI1+RP7yMg7dbK2yE/2vYr4jW3JugHOgtn1GaN6LpdYDE74o8iA21aY98GAmgk/wxPBZZRR8AoUPnwyHTQ11gGlT7dEHWfN4D2Ot0+fJw3m5qSnaJ5LZUjLvZCx9/9tqIgowaOVG3PVJLoGIwxZpOiJKJY8axKQEyNfGcoUTTmHfSQXx3fF7u0oW8XuunF2P2O3LOFCFhCtjqYxv2/3uNiuPuk1ENH3bDTuOzogFsGQGXynCkWnlZTSS1Afz+inI5Aa2L73EDW77BMOoWDQBZucjip0CUhPtUldOWd2lX6fBRL/KyrtTJnxcJHHP8ziMpZ/NGnNIRnZWwhIik1B30RLubO08JiI6e2+NvSnFdlHSSc+Q+5UaJR6RM7aqwPOoT0zgnlDA8Srq4UZiXZrSAzASKb3Suc9S5MjJ+QB2io+ma99sjEemgYndEsd7U2m0JYyXIh1GauLgFr+GUW43XlmjROaPrcSDZBB8WuFI7pX3AJJP32NZXWDuifn+RWFHFNoCWS3QJQ2UUAOtNeSelrbYmCicjHYCXZ4ogzT6tzhH4W5GPvUHmYXE/4YEjnA+Q=
  - secure: OpFhrgclDsBtx9GILkfokjkiFDfgWnZcL0lCyOHEHCJt32nMFyR8aLiPavn5hxHDNVigxt9lsLUuovUut+m81+1YCM5MqQovlqh3kaNSShOsXLn2a6CII9/gHGCBuKVmuu2NHWj5gqloh2bgVdUM7E070K569DXdwl3d79a42FeUiG37CDzzfj13z8c08PROLsu9m6RY/JEYVsKsWZGKC2pE6YKDQMIUHGFaWrkng84DRuOR4zE6x80FXzjXIZ0GS8eGT4EWlXH8o23KpDt/IJkGEt1tWY1ooDOz43LgmSk+fPDio9jclc7zdpIkFp4V9UzzFC6rT8kGb3vMlsjsP4Ctb/8flVC/T9AN29dCIf66THgm17sC7Nj7lNuLDZyk7sv6fFZtuxv3Yx8QhadUZSCi5KgxwX0ZzyYKRX+y5cBSE0NsSB1q1g14IoWDUAam5XRg/We5K/PkMDzDhbWEllwy96/mlQBQrg0jbO9XtFB5BScPf/wG3ZDihMXPe3IoA1AvJ+PPc6DRaHU8ReJHoTudIUXgVmVQPIcP1PlZIaKEu6iIgFWwvh7wO9LD85c+f2x0+1IiXN6pfezP8RVOcW0NilE+tTamofyGnGsTxNdfw800L2NOQouN6lMsrq3r3Ej+3yAKUAbEsJpydY3eSyI/rwILGjfVezkq9aEE8h0=
